name: autogen-docs

on:
  push:
    branches: [master]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    name: generate docs
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - if: github.event_name == 'pull_request'
        run: git fetch --no-tags --depth=1 origin master
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v4.0.0
        with:
          vimdoc: decipher
          pandoc: "README.md"
          version: "NVIM >= v0.8.0"
          toc: true
          description: "A plugin that provides ways to encode and decode text using various codecs like base64."
          demojify: false
          dedupsubheadings: true
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: true
          shiftheadinglevelby: 0
          incrementheadinglevelby: 0
      - name: preview changes
        if: github.event_name == 'pull_request'
        run: git diff --color=always origin/master -- "doc/decipher.txt"
      - uses: stefanzweifel/git-auto-commit-action@v6
        if: github.ref == 'refs/heads/master'
        with:
          commit_message: "Auto-generate docs"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
